#!/bin/bash

repoList=( $CIRCLE_REVERSE_DEPENDENCIES )

for repo in "${repoList[@]}"
do
  echo Triggering CI build $repo && \
  curl -v -X POST https://circleci.com/api/v1/project/redsift/$repo/tree/$CIRCLE_BRANCH?circle-token=$CIRCLE_TOKEN
done
